/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_projet2;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class FenetreAccueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreAccueil.class.getName());

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        
        initComponents();
        setTitle("Bienvenue dans LightOff");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JLabel();
        Regles = new javax.swing.JButton();
        jouerClassique = new javax.swing.JButton();
        jouerVariante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titre.setText(" Bienvenue dans le jeu LightsOff");

        Regles.setText("Regles");
        Regles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReglesActionPerformed(evt);
            }
        });

        jouerClassique.setText("Classique");
        jouerClassique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerClassiqueActionPerformed(evt);
            }
        });

        jouerVariante.setText("Variante");
        jouerVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerVarianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Regles)
                        .addGap(36, 36, 36)
                        .addComponent(jouerClassique)
                        .addGap(54, 54, 54)
                        .addComponent(jouerVariante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regles)
                    .addComponent(jouerClassique)
                    .addComponent(jouerVariante))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReglesActionPerformed
        JOptionPane.showMessageDialog(this,
        "📘 Version Classique :\n" +
        "- Clique sur une cellule pour inverser son état et celui de ses 4 voisines (haut, bas, gauche, droite).\n\n" +
        "📗 Version Variante :\n" +
        "- Clique sur une cellule pour inverser toute sa ligne et toute sa colonne.\n\n" +
        "🎯 Objectif : éteindre toutes les cellules (noires) avec le moins de coups possible.",
        "Règles du jeu LightOff",
        JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_ReglesActionPerformed

    private void jouerClassiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerClassiqueActionPerformed
        new fenetre_jeux(true).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jouerClassiqueActionPerformed

    private void jouerVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerVarianteActionPerformed
        new fenetre_jeux(false).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jouerVarianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreAccueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regles;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton jouerClassique;
    private javax.swing.JButton jouerVariante;
    // End of variables declaration//GEN-END:variables
}
